# Generated by Django 4.2.7 on 2023-11-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nota', models.PositiveSmallIntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
